name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
        - uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'adopt'
        - name: Buid with Gradel
          run: ./gradlew buid
        - name: Gradle Test
          run: ./gradlew test
