name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 17
            uses: actions/setup-java@v2
            with:
              java-version: 17
              distribution: 'adopt'
          - uses: gradle/gradle-build-action@v2
            with:
              arguments: build
          - name: Unit tests
            run: bash ./gradlew test --stacktrace


