name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - steps:
          - name: Checkout project sources
            uses: actions/checkout@v3
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
          - name: Run build with Gradle Wrapper
            run: ./gradlew build
      - name: Gradle Test
        run: ./gradlew test --tests "*"

