name: Java-CI
on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: windows-latest
    steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: 17
              distribution: 'temurin'
              architecture: x64
          - name: Grant permissions  to gradlew
            run: chmod +x gradlew
          - name: JUnit with Gradlew
            run: ./gradlew build


